name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ec2-user@ubu-the-bear.shop << 'EOF'
            cd /home/ec2-user/shopping-mall
            git pull origin main
            docker-compose down
            docker-compose up --build -d
          EOF

